# -*- coding: utf-8 -*-
"""01352101

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LBIPT7TSH-Psl1ozOAxGGHjCDxfQtb1x
"""

!pip install pyngrok line-bot-sdk -q

from flask import Flask, request, abort
from pyngrok import ngrok
import requests
import re

from linebot.v3 import WebhookHandler
from linebot.v3.exceptions import InvalidSignatureError
from linebot.v3.messaging import (
    Configuration,
    ApiClient,
    MessagingApi,
    ReplyMessageRequest,
    TextMessage
)
from linebot.v3.webhooks import MessageEvent, TextMessageContent

# ==============================
# 1. 金鑰與設定
# ==============================

NGROK_AUTHTOKEN = "3EChQt0zFEGpYfTeA9OuBhK0xe8_3aDtdhUULr6BNjgEJs5Fr"
LINE_CHANNEL_SECRET = "7c2b39ba38a789fa207ce41d5ab4ab9b"
LINE_CHANNEL_ACCESS_TOKEN = "K5dcazj+z/q1RrBkvnhNjTHbqsH6ivyoRvwmQP8B6/19635LDdYBWOo6VI/L/wEnCJfh/yQqcfO8KD8CHDPPeytdbsBCHH9eZo1RVOe+o1RVbOzkhUgoMMjqsMdMzHNuM+x4Gh2GYcnMAeaLFU50lgdB04t89/1O/w1cDnyilFU="

app = Flask(__name__)
configuration = Configuration(access_token=LINE_CHANNEL_ACCESS_TOKEN)
handler = WebhookHandler(LINE_CHANNEL_SECRET)

# 儲存使用者模式
user_state = {}

currency_map = {
    "台幣": "TWD", "臺幣": "TWD", "新台幣": "TWD", "TWD": "TWD",
    "美金": "USD", "美元": "USD", "USD": "USD",
    "日幣": "JPY", "日圓": "JPY", "JPY": "JPY",
    "韓幣": "KRW", "韓元": "KRW", "KRW": "KRW",
    "人民幣": "CNY", "RMB": "CNY", "CNY": "CNY"
}

currency_name = {
    "TWD": "台幣", "USD": "美金", "JPY": "日幣", "KRW": "韓幣", "CNY": "人民幣"
}

def get_rate(from_c, to_c):
    try:
        r = requests.get(f"https://open.er-api.com/v6/latest/{from_c}", timeout=10)
        return r.json()["rates"].get(to_c)
    except:
        return None

# ==============================
# 2. 訊息處理邏輯
# ==============================

@app.route("/callback", methods=["POST"])
def callback():
    signature = request.headers.get("X-Line-Signature")
    body = request.get_data(as_text=True)
    try:
        handler.handle(body, signature)
    except InvalidSignatureError:
        abort(400)
    return "OK"

@handler.add(MessageEvent, message=TextMessageContent)
def handle_message(event):
    uid = event.source.user_id
    text = event.message.text.strip()

    # 模式 A: 設定轉換指令
    cmd = re.search(r"(.+)換(.+)", text)
    if cmd:
        c1, c2 = cmd.groups()
        f_code, t_code = currency_map.get(c1.strip()), currency_map.get(c2.strip())
        if f_code and t_code:
            user_state[uid] = {"f": f_code, "t": t_code}
            reply = f"✅ 已切換模式\n{currency_name[f_code]} ➡️ {currency_name[t_code]}\n──────\n請輸入數字，我會顯示明細與對應韓幣。"
        else:
            reply = "❌ 支援幣別：台幣、美金、日幣、韓幣、人民幣。"

    # 模式 B: 輸入金額計算
    else:
        s = user_state.get(uid)
        if not s:
            reply = "⚠️ 請先輸入換匯指令，例如：『美金換台幣』"
        else:
            amounts_raw = re.split(r'[\\s,，+、\n]+', text)
            valid_amounts = []
            for a in amounts_raw:
                try:
                    if a.strip():
                        valid_amounts.append(float(a.strip().replace(',', '')))
                except ValueError:
                    continue

            if not valid_amounts:
                reply = "❓ 請輸入有效的數字金額。"
            else:
                target_rate = get_rate(s['f'], s['t'])
                krw_rate = get_rate(s['f'], "KRW")

                if target_rate and krw_rate:
                    sum_f = sum(valid_amounts)
                    sum_t = sum_f * target_rate

                    detail_lines = []
                    for v in valid_amounts:
                        v_krw = v * krw_rate
                        detail_lines.append(f"• {v:,.0f} {currency_name[s['f']]} (≈ {v_krw:,.0f} 韓幣)")

                    detail_str = "\n".join(detail_lines)

                    reply = f"📝 本次明細與韓幣對照：\n{detail_str}\n"
                    reply += f"──────\n"
                    reply += f"📊 加總換算：\n"
                    reply += f"• 總計 {currency_name[s['f']]}：{sum_f:,.2f}\n"
                    reply += f"• 換算 {currency_name[s['t']]}：{sum_t:,.2f}\n"
                    reply += f"──────\n"
                    reply += f"(匯率：1 {s['f']} = {target_rate:.4f} {s['t']})"
                else:
                    reply = "🌐 匯率連線失敗，請稍後再試。"

    with ApiClient(configuration) as client:
        MessagingApi(client).reply_message(
            ReplyMessageRequest(reply_token=event.reply_token, messages=[TextMessage(text=reply)])
        )

# ==============================
# 3. 啟動服務
# ==============================

ngrok.set_auth_token(NGROK_AUTHTOKEN)
try:
    tunnels = ngrok.get_tunnels()
    for t in tunnels: ngrok.disconnect(t.public_url)
    url = ngrok.connect(5000).public_url
    print(f"你的 Webhook URL 是：\n{url}/callback")
except:
    pass

app.run(port=5000)